apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-html
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-html
  template:
    metadata:
      labels:
        app: demo-html
    spec:
      containers:
        - name: demo-html
          image: hyperbeansrahul/demo-html:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
