apiVersion: v1
kind: Service
metadata:
  name: demo-html
  namespace: default
spec:
  type: NodePort
  selector:
    app: demo-html
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30007

